### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by zbeekman** [benbalter/markdown-to-pdf#11]
If you go to the README.md and click the `this file as a pdf` link, you get an internal server error

**Comment by benbalter** [comment]
Looks like our messages past each other. See https://github.com/benbalter/markdown-to-pdf/pull/9#issuecomment-170589074. Please let me know if the recent changes on master don't resolve your issue. Was able to deploy to a fresh Heroku instance.

**Comment by zbeekman** [comment]
Hey, I think I might have been being a little bit impatient, or that the deploy was still underway when I was testing the fix. Everything works now both on your heroku instance and on mine. :tada: Thanks so much :bow:
