### ISSUE TITLE
internal server error (image assets probably not loading)

### ISSUE THREAD

**Issue by zbeekman** [benbalter/markdown-to-pdf#12]
I was wondering if there was a way to avoid the "internal server error" for pages like: https://github-pdf.herokuapp.com/jacobwilliams/json-fortran/blob/master/README.pdf

I'm guessing this happens when shields.io badges are acting up. Would there be a way to provide some time limit for images to load, and if they don't just insert the alt-text and continue making the PDF?

Perhaps my gut feeling about why this isn't working is wrong, but I'm betting it's due to shields.io biting it.

**Comment by zbeekman** [comment]
bing @benbalter

**Comment by benbalter** [comment]
This would have to be fixed upstream. See https://github.com/pdfkit/pdfkit/issues/279#issuecomment-103266425 and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1888. Until those lower level libraries add per-asset timeout support, I'm afraid there's no easy way to solve this problem.

**Comment by zbeekman** [comment]
Ah too bad, but thanks for getting back to me and closing the issue!
