### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by probonopd** [benbalter/markdown-to-pdf#7]
When I try to access https://github-pdf.herokuapp.com/benbalter/markdown-to-pdf/blob/master/README.pdf I get an Internal Server Error.

**Comment by kofronpi** [comment]
+1

**Comment by benbalter** [comment]
Fixed by https://github.com/benbalter/problem_child/pull/9. Thanks again @probonopd!

**Comment by benbalter** [comment]
(closed the wrong issue)

**Comment by benbalter** [comment]
The personal access token the demo app used was invalidated inadvertently. Created a new token and https://github-pdf.herokuapp.com/benbalter/markdown-to-pdf/blob/master/README.pdf now works.
