### ISSUE TITLE
The content of app.json is not a valid JSON object.

### ISSUE THREAD

**Issue by zbeekman** [benbalter/markdown-to-pdf#8]
I get the following error message when I click the "deploy to heroku" button:
> The content of app.json is not a valid JSON object.

 I have never used heroic before, but just created an account.

![screen shot 2016-01-10 at 7 21 08 pm](https://cloud.githubusercontent.com/assets/279612/12225073/96cc2824-b7cf-11e5-9740-543f9f6a5d72.png)

**Comment by parkr** [comment]
It's probably the trailing comma right on the last line 4.

**Comment by zbeekman** [comment]
Yup, would have probably been smart of me to eyeball the json, or at least throw it at a validator. #9 should fix the issue.
